server:
  port: 8082
logging:
  level:
    org.springframework : INFO
    ir.barook.barokinterview : INFO
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/barook
    username: root
    password: 311117@Me
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    elasticsearch:
      repositories:
        enabled: true
  elasticsearch:
    uris: localhost:9200